branches:
  only:
    - master
    - develop
os: linux
language: node_js
node_js: '10'
cache: npm
before_install:
  - npm i -g npm@latest
  - export PATH="$HOME/node_modules/.bin:$PATH"
script:
  - npm run lint
  - npm run test
  - npm run package:build
  - npm run storybook:build
  - npm run ui-guideline:build
deploy:
  - provider: script
    script: npm run package:publish:ci
    skip_cleanup: true
    on:
      branch: master
  - provider: pages
    skip_cleanup: true
    token: $GITHUB_TOKEN
    keep_history: true
    local_dir: ./dist-storybook
    on:
      all_branches: true
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: ./dist/ui-guideline/browser
    repo: lunit-io/ui-guideline
    on:
      all_branches: true
notifications:
  email:
    on_success: never
    on_failure: always