branches:
  only:
    - master
    - develop
os: linux
language: node_js
node_js: '10'
cache: npm
before_install:
  - npm i -g npm@latest
  - export PATH="$HOME/node_modules/.bin:$PATH"
script:
  - npm run lint
  - npm run test
  - npm run package:build
  - npm run storybook:build
deploy:
  - provider: script
    script: npm run package:publish:ci
    on:
      branch: master
  - provider: pages
    skip_cleanup: true
    token: $GITHUB_TOKEN
    keep_history: true
    local_dir: ./dist-storybook
    on:
      branch: master
notifications:
  email:
    on_success: never
    on_failure: always