yarnPath: '.yarn/releases/yarn-berry.cjs'
packageExtensions:
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  '@chakra-ui/checkbox@*':
    dependencies:
      'framer-motion': '*'
  '@chakra-ui/clickable@*':
    dependencies:
      '@chakra-ui/react-utils': '*'
  '@chakra-ui/system@*':
    dependencies:
      '@chakra-ui/react-utils': '*'
      '@emotion/react': '*'
      '@emotion/styled': '*'
  '@chakra-ui/tooltip@*':
    dependencies:
      '@chakra-ui/react-utils': '*'
  '@chakra-ui/transition@*':
    dependencies:
      'framer-motion': '*'
