name: 'Deploy insight-viewer on staging'

on:
  push:
    branches:
      - develop
    paths:
      - .github/workflows/insight-viewer-staging.yml
      - libs/insight-viewer/**
      - apps/insight-viewer-docs/**

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WORKDIR: .
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: 'master'
      - run: npm ci

      - run: npx nx workspace-lint
      - run: npx nx export insight-viewer-docs

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CDN_FOR_PREVIEW_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.CDN_FOR_PREVIEW_SECRET_KEY }}
          aws-region: us-east-1

      - name: Deploy Docs
        env:
          HOST: insight-viewer.s.lunit.io
        run: |
          aws s3 sync \
            ./dist s3://lunit-cdn-for-preview-virginia/${HOST} \
            --delete
