name: Deploy insight-viewer on develop

on:
  push:
    branches:
      - feature/**
      - chore/**
    paths:
      - .github/workflows/insight-viewer-feature.yml
      - packages/insight-viewer/**
      - apps/insight-viewer-docs/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get short sha
        id: sha7
        run: |
          echo "::set-output name=value::${GITHUB_SHA::7}"
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Yarn build
        id: yarn-build
        run: |
          yarn
          yarn doc:insight-viewer

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:     ${{ secrets.CDN_FOR_PREVIEW_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.CDN_FOR_PREVIEW_SECRET_KEY }}
          aws-region:            us-east-1

      - name: Deploy
        env:
          HOST: insight-viewer--${{ steps.sha7.outputs.value }}.f.lunit.io
        run: |
          aws s3 sync \
            ./dist s3://lunit-cdn-for-preview-virginia/${HOST} \
            --delete
