name: Test: Insight Viewer
on:
  pull_request:
    branches: [master]
  paths:
    - packages/insight-viewer/**
    - apps/insight-viewer-docs/**
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: v1/${{ runner.os }}/node-12/${{ hashFiles('**/package-lock.json') }}
          restore-keys: v1/${{ runner.os }}/node-12/
      - name: Install dependencies
        run: yarn
      - name: Run visual tests
        uses: percy/exec-action@v0.3.1
        with:
          custom-command: 'yarn test'
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
